// <auto-generated />
using MVClayout.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVClayout.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510202408_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("MVClayout.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "New",
                            CategoryId = 1,
                            Description = "Ripe tomatoes with bright flavor, perfect for salads and sauces.",
                            ImageUrl = "~/img/product-1.jpg",
                            Name = "Fresh Tomato",
                            OldPrice = 59000m,
                            Price = 39000m
                        },
                        new
                        {
                            Id = 2,
                            Badge = "New",
                            CategoryId = 1,
                            Description = "Crisp cabbage grown with clean farming methods.",
                            ImageUrl = "~/img/product-2.jpg",
                            Name = "Green Cabbage",
                            OldPrice = 45000m,
                            Price = 29000m
                        },
                        new
                        {
                            Id = 3,
                            Badge = "New",
                            CategoryId = 1,
                            Description = "Sweet carrots with natural color and crunch.",
                            ImageUrl = "~/img/product-3.jpg",
                            Name = "Organic Carrot",
                            OldPrice = 50000m,
                            Price = 35000m
                        },
                        new
                        {
                            Id = 4,
                            Badge = "New",
                            CategoryId = 2,
                            Description = "Juicy oranges rich in vitamin C.",
                            ImageUrl = "~/img/product-4.jpg",
                            Name = "Sweet Orange",
                            OldPrice = 89000m,
                            Price = 69000m
                        },
                        new
                        {
                            Id = 5,
                            Badge = "New",
                            CategoryId = 2,
                            Description = "Crisp apples selected for freshness and taste.",
                            ImageUrl = "~/img/product-5.jpg",
                            Name = "Fresh Apple",
                            OldPrice = 99000m,
                            Price = 79000m
                        },
                        new
                        {
                            Id = 6,
                            Badge = "New",
                            CategoryId = 2,
                            Description = "Naturally sweet bananas for snacks and smoothies.",
                            ImageUrl = "~/img/product-6.jpg",
                            Name = "Garden Banana",
                            OldPrice = 56000m,
                            Price = 42000m
                        },
                        new
                        {
                            Id = 7,
                            Badge = "New",
                            CategoryId = 3,
                            Description = "Fresh broccoli packed for healthy family meals.",
                            ImageUrl = "~/img/product-7.jpg",
                            Name = "Healthy Broccoli",
                            OldPrice = 73000m,
                            Price = 55000m
                        },
                        new
                        {
                            Id = 8,
                            Badge = "New",
                            CategoryId = 3,
                            Description = "A balanced mix of organic vegetables and fruits.",
                            ImageUrl = "~/img/product-8.jpg",
                            Name = "Mixed Organic Box",
                            OldPrice = 189000m,
                            Price = 149000m
                        });
                });

            modelBuilder.Entity("MVClayout.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fresh vegetables for daily meals.",
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Seasonal fruits selected from trusted farms.",
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Healthy organic products ready for your kitchen.",
                            Name = "Fresh Food"
                        });
                });

            modelBuilder.Entity("MVClayout.Models.Product", b =>
                {
                    b.HasOne("MVClayout.Models.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MVClayout.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
