// <auto-generated />
using MVClayout.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVClayout.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511170750_FixProductNamesToMatchImages")]
    partial class FixProductNamesToMatchImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("MVClayout.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "New",
                            CategoryId = 1,
                            Description = "Ripe tomatoes with bright flavor, perfect for salads and sauces.",
                            ImageUrl = "~/img/product-1.jpg",
                            Name = "Fresh Tomato",
                            OldPrice = 59000m,
                            Price = 39000m
                        },
                        new
                        {
                            Id = 2,
                            Badge = "New",
                            CategoryId = 2,
                            Description = "Sweet and juicy pineapple, great for dessert and juice.",
                            ImageUrl = "~/img/product-2.jpg",
                            Name = "Fresh Pineapple",
                            OldPrice = 65000m,
                            Price = 49000m
                        },
                        new
                        {
                            Id = 3,
                            Badge = "New",
                            CategoryId = 1,
                            Description = "Fresh organic chili for spicy and flavorful cooking.",
                            ImageUrl = "~/img/product-3.jpg",
                            Name = "Organic Chili",
                            OldPrice = 50000m,
                            Price = 35000m
                        },
                        new
                        {
                            Id = 4,
                            Badge = "New",
                            CategoryId = 2,
                            Description = "Fresh strawberries with natural sweetness and aroma.",
                            ImageUrl = "~/img/product-4.jpg",
                            Name = "Sweet Strawberry",
                            OldPrice = 89000m,
                            Price = 69000m
                        },
                        new
                        {
                            Id = 5,
                            Badge = "New",
                            CategoryId = 1,
                            Description = "Crunchy cucumber for salads and healthy snacks.",
                            ImageUrl = "~/img/product-5.jpg",
                            Name = "Fresh Cucumber",
                            OldPrice = 45000m,
                            Price = 32000m
                        },
                        new
                        {
                            Id = 6,
                            Badge = "New",
                            CategoryId = 1,
                            Description = "Bright red vine tomato for daily family meals.",
                            ImageUrl = "~/img/product-6.jpg",
                            Name = "Vine Tomato",
                            OldPrice = 52000m,
                            Price = 37000m
                        },
                        new
                        {
                            Id = 7,
                            Badge = "New",
                            CategoryId = 1,
                            Description = "Soft and creamy baby potatoes for roasting and soup.",
                            ImageUrl = "~/img/product-7.jpg",
                            Name = "Baby Potato",
                            OldPrice = 62000m,
                            Price = 46000m
                        },
                        new
                        {
                            Id = 8,
                            Badge = "New",
                            CategoryId = 2,
                            Description = "Naturally sweet bananas for snacks and smoothies.",
                            ImageUrl = "~/img/product-8.jpg",
                            Name = "Garden Banana",
                            OldPrice = 56000m,
                            Price = 42000m
                        });
                });

            modelBuilder.Entity("MVClayout.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fresh vegetables for daily meals.",
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Seasonal fruits selected from trusted farms.",
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Healthy organic products ready for your kitchen.",
                            Name = "Fresh Food"
                        });
                });

            modelBuilder.Entity("MVClayout.Models.Product", b =>
                {
                    b.HasOne("MVClayout.Models.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MVClayout.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
